import { StateProvider } from "@/providers/StateProvider";
import reducer, { initialState } from "@/store/reducer";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={` ${roboto.className} ${styles.main}`}>
        <StateProvider initialState={initialState} reducer={reducer}>
          <Component {...pageProps} />
        </StateProvider>
      </main>
    </>
  );
}
