import { StateProvider } from "@/providers/StateProvider";
import reducer, { initialState } from "@/store/reducer";
import { ThemeProvider } from "@mui/material/styles";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Roboto } from "next/font/google";
import { QueryClientProvider, QueryClient } from "react-query";
import { queryClient } from "@/services/queryClient";
import theme from "@/providers/theme-service";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider theme={theme}>
      <StateProvider initialState={initialState} reducer={reducer}>
        <QueryClientProvider client={queryClient}>
          <Head>
            <title>GovOne - Pesquisa</title>
            <meta name="description" content="Generated by André Santos" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
          </Head>
          <main className={` ${roboto.className} ${styles.main}`}>
            <Component {...pageProps} />
          </main>
        </QueryClientProvider>
      </StateProvider>
    </ThemeProvider>
  );
}
